- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Install PostgreSQL
  apt: pkg=postgresql state=latest update_cache=true
