- name: Create deployment directory
  file: path={{ app_name }} owner={{ user }} group={{ user }} state=directory

- name: Make shared directories
  file: path={{ app_name }}/shared/{{ item }} group={{ user }} owner={{ user }} state=directory
  with_items:
    - config
    - config/unicorn
  tags: shared

- name: Install database.yml
  template: src=database.yml.j2 dest={{ app_name }}/shared/config/database.yml force=yes mode=755 owner={{ user }}

- name: Add unicorn shared/config
  template: src=unicorn.rb.j2 dest={{ app_name }}/shared/config/unicorn/production.rb force=yes mode=755
  tags: unicorn
